In [1]:
pip install numpy

In [2]:
import numpy as np


In [3]:
a = np.array([1,2,3])
print(a)


[1 2 3]


In [4]:
type(a)

numpy.ndarray

In [2]:
b = np.array([[1,2,3], [4,5,6], [5,6,7]])
print(b)

[[1 2 3]
 [4 5 6]
 [5 6 7]]


In [6]:
c = np.array([[1,2,3], [4,4.0,6]])
print(c)

[[1. 2. 3.]
 [4. 4. 6.]]


In [7]:
d = np.array([[1,2,3], [4,4,6],[7,8,9]])
print(d)

[[1 2 3]
 [4 4 6]
 [7 8 9]]


In [9]:
li_arr = [i for i in range(100)]
print(li_arr)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [10]:
print("Type of array: ",type(li_arr))

Type of array:  <class 'list'>


In [11]:
import sys
print("How much size one element take: ",sys.getsizeof(li_arr[0]))

How much size one element take:  28


In [12]:
print("How much size one element take: ",sys.getsizeof(li_arr[99]))

How much size one element take:  28


In [13]:
print("How much size list array take: ",(sys.getsizeof(li_arr[0]))*len(li_arr))

How much size list array take:  2800


In [14]:
np_arr = np.arange(100)
print(np_arr)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [15]:
print("How much size one element take: ",np_arr.itemsize)


How much size one element take:  4


In [16]:
print("How much size list array take: ",np_arr.itemsize*np_arr.size)

How much size list array take:  400


In [17]:
import time
li_arr1=[i for i in range(100000)]
li_arr2=[i for i in range(100000)]
start_time=time.time()
li_add=[li_arr1[i]+li_arr2[i] for i in range(100000)]
final_time=time.time()
print("Time taken by Lists to perform addition: ",(final_time-start_time))

Time taken by Lists to perform addition:  0.011437416076660156


In [18]:
import time
np_arr1=np.arange(100000)
np_arr2=np.arange(100000)
start_time=time.time()
np_add=np_arr1+np_arr2
final_time=time.time()
print("Time taken by Lists to perform addition: ",(final_time-start_time))

Time taken by Lists to perform addition:  0.002998828887939453


In [19]:
li_arr1=[i for i in range(10)]
li_arr2=[i for i in range(10)]
li_add=[li_arr1[i]+li_arr2[i] for i in range(10)]
print(li_add)
print()
np_arr1=np.arange(10)
np_arr2=np.arange(10)
np_add=np_arr1+np_arr2
print(np_add)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

[ 0  2  4  6  8 10 12 14 16 18]


In [3]:
np.empty(shape = (2,3) , dtype=float)

array([[-1.33364029e-311, -2.56641854e+106,  1.33364828e-311],
       [ 1.33364828e-311,  5.43472210e-323,  4.94065646e-324]])

In [4]:
x = np.empty([3,3], dtype=int)
print(x)

[[      0       1       0]
 [5570652    1000       0]
 [    768       0 7209057]]


In [5]:
print(np.zeros(shape = (2,3), dtype=float))

[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
abc = np.array([[[1,2,3],[4,5,6]]])
print(abc)
print(abc.ndim)

[[[1 2 3]
  [4 5 6]]]
3


In [8]:
import numpy as np
x = np.arange(5) #default value of start is 0 and step is 1
print(x)

[0 1 2 3 4]


In [9]:
import numpy as np
x = np.arange(1,11) #default value of step is 1
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [10]:
import numpy as np
x = np.arange(1,11, 2) #default value of step is 1
print(x)

[1 3 5 7 9]


In [11]:
import numpy as np
x = np.linspace(1,100, num=70)
print(x)

[  1.           2.43478261   3.86956522   5.30434783   6.73913043
   8.17391304   9.60869565  11.04347826  12.47826087  13.91304348
  15.34782609  16.7826087   18.2173913   19.65217391  21.08695652
  22.52173913  23.95652174  25.39130435  26.82608696  28.26086957
  29.69565217  31.13043478  32.56521739  34.          35.43478261
  36.86956522  38.30434783  39.73913043  41.17391304  42.60869565
  44.04347826  45.47826087  46.91304348  48.34782609  49.7826087
  51.2173913   52.65217391  54.08695652  55.52173913  56.95652174
  58.39130435  59.82608696  61.26086957  62.69565217  64.13043478
  65.56521739  67.          68.43478261  69.86956522  71.30434783
  72.73913043  74.17391304  75.60869565  77.04347826  78.47826087
  79.91304348  81.34782609  82.7826087   84.2173913   85.65217391
  87.08695652  88.52173913  89.95652174  91.39130435  92.82608696
  94.26086957  95.69565217  97.13043478  98.56521739 100.        ]


In [12]:
import numpy as np
x = np.linspace(1,100,25)
print(x)

[  1.      5.125   9.25   13.375  17.5    21.625  25.75   29.875  34.
  38.125  42.25   46.375  50.5    54.625  58.75   62.875  67.     71.125
  75.25   79.375  83.5    87.625  91.75   95.875 100.   ]


In [13]:
# default base is 10
a = np.logspace(1.0, 50.0, num = 10)
print(a)

[1.00000000e+01 2.78255940e+06 7.74263683e+11 2.15443469e+17
 5.99484250e+22 1.66810054e+28 4.64158883e+33 1.29154967e+39
 3.59381366e+44 1.00000000e+50]


In [15]:
a=np.array([1,2,3])
b=np.array([[1,2,3],[4,5,6]])
print("Array a is:",a)
print("Array b is: ",b)
print("\nNo. of dimension of a: ",a.ndim)
print("No. of dimension of b: ",b.ndim)
print("\nShape of array a: ",a.shape)
print("Shape of array b: ",b.shape)
print("\nSize of a: ",a.size)
print("Size of b: ",b.size)
print("\nData type of a: ",a.dtype)
print("Data type of b: ",b.dtype)
print("\nItemsize of a: ",a.itemsize)
print("Itemsize of a: ",b.itemsize)
print("\nData of a is: ",a.data)
print("Data of b is: ",b.data)

Array a is: [1 2 3]
Array b is:  [[1 2 3]
 [4 5 6]]

No. of dimension of a:  1
No. of dimension of b:  2

Shape of array a:  (3,)
Shape of array b:  (2, 3)

Size of a:  3
Size of b:  6

Data type of a:  int32
Data type of b:  int32

Itemsize of a:  4
Itemsize of a:  4

Data of a is:  <memory at 0x000002747E73A140>
Data of b is:  <memory at 0x000002747E7FB510>


In [47]:
import numpy as np
from scipy.stats import chi2_contingency

data = np.array([[40,20],[30,10]])
chi2, p, df, expected = chi2_contingency(data)
chi2, p

(0.44642857142857145, 0.5040358664525046)

In [1]:
import numpy as np
x = np.zeros([3,5], dtype=int)
print(x)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [2]:
x = np.ones(5)
print(x)

[1. 1. 1. 1. 1.]


In [3]:
x = np.ones([3,3])
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [4]:
import numpy as np
x = np.arange(1,11) #default value of step is 1
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
x = np.arange(1,10,2)
print(x)

[1 3 5 7 9]


In [6]:
x = np.linspace(1,100)
print(x)

[  1.           3.02040816   5.04081633   7.06122449   9.08163265
  11.10204082  13.12244898  15.14285714  17.16326531  19.18367347
  21.20408163  23.2244898   25.24489796  27.26530612  29.28571429
  31.30612245  33.32653061  35.34693878  37.36734694  39.3877551
  41.40816327  43.42857143  45.44897959  47.46938776  49.48979592
  51.51020408  53.53061224  55.55102041  57.57142857  59.59183673
  61.6122449   63.63265306  65.65306122  67.67346939  69.69387755
  71.71428571  73.73469388  75.75510204  77.7755102   79.79591837
  81.81632653  83.83673469  85.85714286  87.87755102  89.89795918
  91.91836735  93.93877551  95.95918367  97.97959184 100.        ]


In [10]:
x = np.linspace(1,20, num = 10, dtype = float)
print(x)

[ 1.          3.11111111  5.22222222  7.33333333  9.44444444 11.55555556
 13.66666667 15.77777778 17.88888889 20.        ]


In [11]:
a = np.logspace(1, 50)
print(a)

[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09 1.e+10
 1.e+11 1.e+12 1.e+13 1.e+14 1.e+15 1.e+16 1.e+17 1.e+18 1.e+19 1.e+20
 1.e+21 1.e+22 1.e+23 1.e+24 1.e+25 1.e+26 1.e+27 1.e+28 1.e+29 1.e+30
 1.e+31 1.e+32 1.e+33 1.e+34 1.e+35 1.e+36 1.e+37 1.e+38 1.e+39 1.e+40
 1.e+41 1.e+42 1.e+43 1.e+44 1.e+45 1.e+46 1.e+47 1.e+48 1.e+49 1.e+50]


In [12]:
np.random.rand(2)

array([0.67096677, 0.10149957])

In [15]:
np.random.rand(3,3)

array([[0.70429289, 0.24007934, 0.3605886 ],
       [0.06130739, 0.18882368, 0.25705169],
       [0.99303783, 0.31272872, 0.68778785]])

In [16]:
import numpy as np
np.random.randn(3,3)

array([[-1.62517744, -0.30955799,  0.10990334],
       [ 1.03672219,  1.11196145, -0.20141735],
       [-0.22788249, -0.4113158 , -0.38226322]])

In [18]:
arr = np.array([[1, 2, 3, 4, 5, 6],[7, 8, 9, 10, 11, 12]])
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [19]:
newarr = arr.reshape(6, 2) #reshaping the arr into 6×2 matrix
print(newarr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [20]:
newarr2 = arr.reshape(12, 1) #reshaping the arr into 6×2 matrix
print(newarr2)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


In [21]:
newarr3 = arr.reshape(10, 1) #reshaping the arr into 6×2 matrix
print(newarr3)

ValueError: cannot reshape array of size 12 into shape (10,1)

In [22]:
newarr4 = arr.reshape(4, 3) #reshaping the arr into 6×2 matrix
print(newarr4)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [30]:
arr=np.array([1,2,3,4,5,6,7,8])
newarr=arr.reshape(2,-2)
print(newarr)

[[1 2 3 4]
 [5 6 7 8]]


In [33]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(-1,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [34]:
y = np.array([[1,1], [1,1]])
y.flatten()

array([1, 1, 1, 1])

In [40]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
ravel_arr=arr.ravel()
flatten_arr=arr.flatten()
print("Array is: \n",arr)
print("Ravel array: ",ravel_arr)
print("Flatten array: ",flatten_arr)
print("************************************")
flatten_arr[0]=22
print(arr)
print(flatten_arr)
print("************************************")
ravel_arr[0]=22
print(arr)
print("************************************")
print(flatten_arr)
print(ravel_arr)

Array is: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Ravel array:  [1 2 3 4 5 6 7 8 9]
Flatten array:  [1 2 3 4 5 6 7 8 9]
************************************
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[22  2  3  4  5  6  7  8  9]
************************************
[[22  2  3]
 [ 4  5  6]
 [ 7  8  9]]
************************************
[22  2  3  4  5  6  7  8  9]
[22  2  3  4  5  6  7  8  9]


In [41]:
arr=np.array([88,19,46,74,94])
print(arr[1])

19


In [6]:
import numpy as np
arr=np.array([[81,19,46,74,94],[69,79,26,7,29],[21,45,12,80,72],[28,53,65,72,84]])
print(arr)
print("\n")
print(arr[0]) #it will print first row
print("\n")
print(arr[1]) #it will print second row
print("\n")
print(arr[0][1]) #it will print second element of first row
print(arr[2][1]) #it will print second element of third row.

[[81 19 46 74 94]
 [69 79 26  7 29]
 [21 45 12 80 72]
 [28 53 65 72 84]]


[81 19 46 74 94]


[69 79 26  7 29]


19
45


In [7]:
arr=np.array([88,19,46,74,94])
print(arr[-1])
print(arr[-2])
print(arr[-3])

94
74
46


In [8]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,-1])

10


In [9]:
arr=np.array([0,1,2,3,4,5,6,7,8,9,10])
print(arr[:5])

[0 1 2 3 4]


In [48]:
arr=np.array([0,1,2,3,4,5,6,7,8,9,10])
print(arr[::-1])

[10  9  8  7  6  5  4  3  2  1  0]


In [49]:
arr=np.array([0,1,2,3,4,5,6,7,8,9,10])
print(arr[4:10:2])

[4 6 8]


In [11]:
arr=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18]])
print(arr[0,1:5])

[2 3 4 5]


In [15]:
arr=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18]])
print(arr[0:3,1])

[ 2  8 14]


In [52]:
arr=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18]])
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


In [54]:
print(arr[0:2,1])

[2 8]


In [55]:
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [58]:
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [59]:
arr=np.array([1,2,3,4])
x=arr.copy()
y=arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4]


In [62]:
arr = np.array([1,2,3,4,5])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5


In [65]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr)
for x in np.nditer(arr):
    print(x)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
1
2
3
4
5
6
7
8


In [67]:
arr=np.array([1,2,3])
for idx,x in np.ndenumerate(arr):
    print("In index {} element present is {}".format(idx,x))

In index (0,) element present is 1
In index (1,) element present is 2
In index (2,) element present is 3


In [17]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for idx,x in np.ndenumerate(arr):
    print("In index {} element present is {}".format(idx,x))
    
    
print(arr)

In index (0, 0, 0) element present is 1
In index (0, 0, 1) element present is 2
In index (0, 1, 0) element present is 3
In index (0, 1, 1) element present is 4
In index (1, 0, 0) element present is 5
In index (1, 0, 1) element present is 6
In index (1, 1, 0) element present is 7
In index (1, 1, 1) element present is 8
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [16]:
arr1 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr2 = arr1.copy()

for idx,x in np.ndenumerate(arr2):
    arr2[idx] = x*x
    

print(arr2)

[[[ 1  4]
  [ 9 16]]

 [[25 36]
  [49 64]]]


In [3]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2),axis=0)
print(arr)

[1 2 3 4 5 6]


In [4]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

AxisError: axis 1 is out of bounds for array of dimension 1

In [5]:
arr1=np.array([[1,1,1],[1,1,1]])
arr2=np.array([[9,9,9,],[9,9,9]])
arr=np.concatenate((arr1,arr2),axis=0)
print(arr)

[[1 1 1]
 [1 1 1]
 [9 9 9]
 [9 9 9]]


In [6]:
arr1=np.array([[1,1,1],[1,1,1]])
arr2=np.array([[9,9,9,],[9,9,9]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 1 1 9 9 9]
 [1 1 1 9 9 9]]


In [7]:
arr1=np.array([0,0])
arr2=np.array([1,1])
arr=np.hstack((arr1,arr2))
print(arr)

[0 0 1 1]


In [8]:
arr1=np.array([0,0])
arr2=np.array([1,1])
arr=np.vstack((arr1,arr2))
print(arr)

[[0 0]
 [1 1]]


In [9]:
arr1=np.array([[0,0],[0,0]])
arr2=np.array([[1,1],[1,1]])
arr=np.hstack((arr1,arr2))
print(arr)

[[0 0 1 1]
 [0 0 1 1]]


In [10]:
arr1=np.array([[0,0],[0,0]])
arr2=np.array([[1,1],[1,1]])
arr=np.vstack((arr1,arr2))
print(arr)

[[0 0]
 [0 0]
 [1 1]
 [1 1]]


In [11]:
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,2)
print(newarr)

[array([1, 2, 3]), array([4, 5, 6])]


In [12]:
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [13]:
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [14]:
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,8)
print(newarr)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int32), array([], dtype=int32)]


In [12]:
arr=np.array([1,2,3,4,5,6,7])
newarr=np.array_split(arr,3)
print(newarr)

[array([1, 2, 3]), array([4, 5]), array([6, 7])]


In [14]:
arr=np.array([1,2,3,4,5,6,7])
newarr=np.array_split(arr,9)
print(newarr)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([7]), array([], dtype=int32), array([], dtype=int32)]


In [15]:
arr=np.array([1,2,3,4,5,6])
newarr=np.hsplit(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [15]:
arr=np.array([1,2,3,4,5,6])
newarr=np.hsplit(arr,6)
print(newarr)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]


In [17]:
arr=np.array([1,2,3,4,5,6])
newarr=np.hsplit(arr,4)
print(newarr)

ValueError: array split does not result in an equal division

In [18]:
arr=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])
newarr=np.hsplit(arr,2)
print(newarr)

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [19]:
arr=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])
newarr=np.vsplit(arr,2)
print(newarr)

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


In [19]:
arr=np.array([1,2,3,4,5,6,7])
x=np.where(arr==4)
print(x)

(array([3], dtype=int64),)


In [28]:
arr=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])
x=np.where(arr==8)
print(x)


(array([2], dtype=int64), array([0], dtype=int64))


In [29]:
arr1=np.array([[1,2,3,4],[5,6,7,8]])
Y=np.where(arr1==4)
print(Y)

(array([0], dtype=int64), array([3], dtype=int64))


In [2]:
import numpy as np

In [3]:
arr=np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [5]:
arr

array([3, 2, 0, 1])

In [4]:
arr1=np.array([[3,2,0,1],[2,8,1,7]])
print(np.sort(arr1))

[[0 1 2 3]
 [1 2 7 8]]


In [7]:
arr=np.array([41,42,43,44])
x=[True,False,True,False]
print(arr[1])
newarr=arr[x]
print(newarr)


42
[41 43]


In [19]:
arr3=np.array([[3,2],[8,1]])
y = [[True, False],[False, True]]
print(arr3)
arr3[y]

[[3 2]
 [8 1]]


array([3, 1])

In [9]:
arr=np.array([41,42,43,44])
filter_arr=[]       
for elements in arr:
    if elements>42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
        
newarr=arr[filter_arr]
print(newarr)

[43 44]


In [16]:
A=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
B=np.matrix([[10,20,30],[40,50,60],[70,80,90]])
print("Multiplication of matrix A and B using dot method: \n",np.dot(A,B))
print("Multiplication of matrix A and B using matmul method: \n",np.matmul(A,B))

Multiplication of matrix A and B using dot method: 
 [[ 300  360  420]
 [ 660  810  960]
 [1020 1260 1500]]
Multiplication of matrix A and B using matmul method: 
 [[ 300  360  420]
 [ 660  810  960]
 [1020 1260 1500]]


In [10]:
A = np.matrix([[1,2,3],[0,1,4],[5,6,0]])
print("Matrix A is: \n",A)
B=np.linalg.inv(A)
print("Inverse of matrix A is: \n",B)

Matrix A is: 
 [[1 2 3]
 [0 1 4]
 [5 6 0]]
Inverse of matrix A is: 
 [[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


In [31]:
A=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix A is: ",A)
B=np.linalg.matrix_power(A,2)
print("Power of matrix A is: ",B)

Matrix A is:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Power of matrix A is:  [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [3]:
A=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix A is: ",A)
B=np.mean(A)
print("Mean of matrix A is: ",B)

Matrix A is:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Mean of matrix A is:  5.0


In [ ]:
A=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix A is: ",A)
B=np.linalg.det()
print("Power of matrix A is: ",B)

In [18]:
A=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
B=np.matrix([[10,20,30],[40,50,60],[70,80,90]])

print("Transpose of A: \n",A.transpose())
print("Transpose of B: \n",B.transpose())

Transpose of A: 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Transpose of B: 
 [[10 40 70]
 [20 50 80]
 [30 60 90]]


In [20]:
import numpy as np
A=np.matrix([[2,3,1],[6,5,2],[1,4,7]])
print("Matrix A is: \n",A)
B=np.linalg.det(A)
print("Determinant of matrix A is: ",B)

Matrix A is: 
 [[2 3 1]
 [6 5 2]
 [1 4 7]]
Determinant of matrix A is:  -46.99999999999999


Practice Questions

In [9]:
import numpy as np
arr = np.array([10,12])
print(arr)

[10 12]


Q. Create an integer array of size 10. Where all the values should be 0 but the fifth
value should be 1.
Print the elements of array

In [22]:
arr=np.zeros(10)
arr[4]=1
print(arr)
arr

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

Q. Want to take an input from the user for the dimensions of an array and crate two arrays of the same size one would be an empty, and the second would be filled wioth zeros

In [23]:
rows = int(input("Enter number of rows: "))
cols = int(input("Enter number of columns: "))

arr = np.empty((rows, cols))

print(arr)



Enter number of rows: 3
Enter number of columns: 3
[[2. 3. 1.]
 [6. 5. 2.]
 [1. 4. 7.]]


In [24]:
arr = np.zeros((rows, cols))
print(arr)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
arr = np.array((rows, cols))
arr

array([2, 3])

In [16]:
arr = np.random.rand(rows, cols)
arr

array([[0.6800424 , 0.96231054, 0.18166658],
       [0.1662473 , 0.54907366, 0.22016264]])

In [11]:
arr = np.random.random((3,2))
arr

array([[0.77354051, 0.69997224],
       [0.08691004, 0.10480068],
       [0.28583281, 0.49746732]])

In [12]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
arr = np.random.random((3,2))
arr

array([[0.11745964, 0.30772708],
       [0.78296521, 0.63832108],
       [0.59834032, 0.82543833]])

In [15]:
Z_score = (arr- np.mean(arr))/np.std(arr)
print(Z_score)

[[-1.6859659  -0.93573743]
 [ 0.93813638  0.36780156]
 [ 0.21015661  1.10560879]]


In [18]:
m = int(input("Enter number of rows: "))
n = int(input("Enter number of columns: "))

arr = np.array([m,n])
arr


Enter number of rows: 2
Enter number of columns: 3


array([2, 3])

Q. create an array of n dimensions ( taken from user) and create empty arrray. then create empty array and take input from user according the dimensions and print the filled array

np.ndindex(dims)
- Automatically genrate all index combinations
- works on any number of dimensions


In [ ]:
d1 = int(input("Enter dimensions (space separated): "))
d2 = int(input("Enter dimensions (space separated): "))

dim = (d1,d2)

In [2]:
import numpy as np

# Step 1: Take dimensions from user

dims = tuple(map(int, input("Enter dimensions (space separated): ").split()))

# Step 2: Create empty array
arr = np.empty(dims)

# Step 3: Take input for each element

for index in np.ndindex(dims):
    arr[index] = float(input(f"Enter value at index {index}: "))

# Step 4: Print filled array
print("\nFilled Array:")
print(arr)   



Enter dimensions (space separated): 2 3
Enter value at index (0, 0): 1
Enter value at index (0, 1): 2
Enter value at index (0, 2): 3
Enter value at index (1, 0): 4
Enter value at index (1, 1): 5
Enter value at index (1, 2): 6

Filled Array:
[[1. 2. 3.]
 [4. 5. 6.]]


#Assignment Questions:

🟢 Level 1 — Basics & Array Creation

Take n from the user and create a 1D array of squares from 1 to n.

Create a 2D array where each row is [1, 2, 3, ..., n].

Take matrix dimensions from the user and create:

zeros array

ones array

identity matrix

Create an array of size n with random integers between 10 and 50.

Reverse a NumPy array without using loops.

Replace all even numbers in an array with 0.

🟡 Level 2 — Indexing, Slicing & Logic

Extract all elements greater than the mean of the array.

From a 2D array, extract:

first row

last column

diagonal elements

Count how many elements are divisible by 3 and 5.

Replace all negative values in an array with their absolute values.

Swap two columns in a 2D array.

Find indices of elements greater than 90.

Check if two arrays are equal (element-wise).

🟠 Level 3 — Shape Manipulation & Broadcasting

Reshape a 1D array into a user-defined matrix.

Convert a 3D array into a 2D array.

Add a 1D array to each row of a 2D array (broadcasting).

Normalize an array (scale values between 0 and 1).

Stack two arrays:

vertically

horizontally

Split an array into equal-sized chunks.

Pad a matrix with a border of zeros.

🔵 Level 4 — Math, Stats & Aggregation

Compute:

row-wise sum

column-wise mean

overall standard deviation

Find the second largest element without sorting.

Compute dot product of two matrices.

Find correlation between two arrays.

Replace values above the 90th percentile with the percentile value.

Identify outliers using Z-score.

Compute moving average of window size k.

🔴 Level 5 — Advanced & Interview-Grade

Generate a magic square using NumPy.

Create a checkerboard pattern (0s and 1s).

Find rows in a matrix where sum > threshold.

Implement one-hot encoding using NumPy only.

Randomly shuffle rows of a 2D array.

Find unique rows in a matrix.

Compute pairwise Euclidean distance between rows.

Implement softmax function using NumPy.

Convert a categorical array into numeric labels.

🟣 Level 6 — Real Data Analytics Scenarios

Given sales data (days × products), find:

best-selling product

worst-selling day

Fill missing values (NaN) with:

column mean

column median

Standardize features (mean=0, std=1).

Simulate rolling dice 10,000 times and plot probability distribution.

Compute confusion matrix using NumPy.

Apply Min-Max scaling manually.

🧠 Bonus — Thinking Questions (Very Important)

Why is NumPy faster than Python lists?

Difference between reshape() and resize()?

When does broadcasting fail?

Difference between np.empty() and np.zeros()?

How does NumPy handle memory internally?

Why vectorization is faster than loops?

Ex. Daily Sales Tracking (Business Use)

Daily sales for 7 days.
Find:

1. total sales

2. best day

3. worst day

In [23]:
import numpy as np

sales = np.array([1200, 1500, 900, 1800, 1600, 1100, 2000])

print("Total Sales:", sales.sum())
print("Best Day Sales:", sales.max())
print("Worst Day Sales:", sales.min())

Total Sales: 10100
Best Day Sales: 2000
Worst Day Sales: 900
